### ISSUE TITLE
Notification of change of default in ament_cmake_auto

### ISSUE THREAD

**Issue by dhood** [GroupOfRobots/RysROS2#1]
I've seen that you're using `ament_cmake_auto` in your packages and would like to let you know that the default installation behaviour for executables has changed to installing executables to `lib/<package_name>` so they can be used with `ros2 run` (see https://github.com/ament/ament_cmake/pull/97). If you would like to continue installing executables to `bin` you can change your `ament_package()` calls to be `ament_package(INSTALL_TO_PATH)`.

Opening and closing this issue just as a notification.

**Comment by mjbogusz** [comment]
Thanks for notification. I'm reopening as a reminder to myself to look into that later.

**Comment by mjbogusz** [comment]
Closing as all packages' `CMakeLists.txt` files have been rewritten so that they don't use `ament_auto` at all.
